[workspace]
resolver = "2"
members = ["proxygen", "proxygen-macros", "tests"]
default-members = ["proxygen", "proxygen-macros"]

[workspace.package]
authors = ["Warren Hood <nullbyte001@gmail.com>"]
version = "0.5.1"
edition = "2024"
description = "A DLL proxy generator written in Rust"
license = "MIT"
repository = "https://github.com/WarrenHood/proxygen/"